### ISSUE TITLE
(ThunderSTORM plugin) Error when exporting a table (csv file) from ThunderSTORM

### ISSUE THREAD

**Issue by cleterrier** [imodpasteur/smlm-file-format#1] opened 2018-08-22 21:12 UTC
I installed the plugin (SMLM_ThunderSTORM-0.1.0-SNAPSHOT-jar-with-dependencies) in my plugin folder. I imported a ThunderSTORM csv table; the file is available [here](https://drive.google.com/file/d/1ZrPp8dMeLYkNsZx3u0tu6pA6sV0H_PdB/view?usp=sharing) for testing. I then tried to export it as SMLM format using the following settings:

<img width="533" alt="export" src="https://user-images.githubusercontent.com/1062283/44491109-839d5e80-a660-11e8-92bf-e948d55afbeb.png">

I got the following error:

```
(Fiji Is Just) ImageJ 2.0.0-rc-68/1.52e; Java 1.8.0_151 [64-bit]; Mac OS X 10.13.6; 624MB of 10667MB (5%)
 
java.lang.AbstractMethodError: org.imod.io.SmlmThunderSTORM.exportToFile(Ljava/lang/String;ILcz/cuni/lf1/lge/ThunderSTORM/results/GenericTable;Ljava/util/List;)V
	at cz.cuni.lf1.lge.ThunderSTORM.ImportExportPlugIn.callExporter(ImportExportPlugIn.java:247)
	at cz.cuni.lf1.lge.ThunderSTORM.ImportExportPlugIn.runExport(ImportExportPlugIn.java:177)
	at cz.cuni.lf1.lge.ThunderSTORM.ImportExportPlugIn.run(ImportExportPlugIn.java:84)
	at ij.IJ.runUserPlugIn(IJ.java:228)
	at ij.IJ.runPlugIn(IJ.java:192)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at cz.cuni.lf1.lge.ThunderSTORM.UI.MacroParser.runNestedWithRecording(MacroParser.java:174)
	at cz.cuni.lf1.lge.ThunderSTORM.results.ResultsTableWindow$4.actionPerformed(ResultsTableWindow.java:104)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by cleterrier** [comment] 2018-08-22 21:28
I have edited the previous message multiple times, including the error message that was incomplete in my initial posting. If you received the issue by email alert, please look at the latest version directly on GitHub.

**Comment by oeway** [comment] 2018-08-23 08:53
Hey, thanks for the bug report.
Our plugin has tested with only the release ThunderSTORM Version 1.3.

And We noticed that the Plugin interface in the latest ThunderSTORM releases has been changed. So, we released a newer version which compatible with newer versions of ThunderSTORM.

Please feel free to try it out here: https://github.com/imodpasteur/smlm-file-format/releases/tag/v0.1.1

We will update the document for this two different cases.

**Comment by cleterrier** [comment] 2018-08-23 09:03
Hi, thanks! 

I Just tested and the 0.1.1 version works for me. My ThundersSTORM version is based on @zitmen's dev-2016-09-10-b1latest beta, with phasor added from @kjamartens: https://github.com/kjamartens/thunderstorm/tree/master/Compiled%20plugin. 

I don't think the phasor function has been integrated in a ThunderSTORM release from @zitmen yet. Maybe the best would be for someone to make a new "reference" ThunderSTORM build via a branch that incorporates phasor, SMLM format and possibly other upgrades has it seems that @zitmen doesn't work on it anymore?

**Comment by oeway** [comment] 2018-08-23 09:25
Great to hear that it worked.

I see your idea.  I think that can be also done with the `collaborators` feature on Github. If possible, @zitmen could add a few other people who can maintain the library to the existing ThunderSTORM repo. 

For adding the phasor and SMLM format etc., we just need to fork the ThunderSTORM repo and send pull request.

Those ones who have access to the repo need to review pull requests, test them, and accept them to the ThunderSTORM repo. 

@cleterrier @kjamartens @zitmen @benoitbenoit

**Comment by cleterrier** [comment] 2018-08-23 09:29
I think this is what @kjamarten has done for phasor. But for the average user, what is important is to get new build/release as soon as new code is added because they don't know how to build ThunderSTORM from source.

**Comment by oeway** [comment] 2018-08-23 09:39
That's right, I think here the problem is @zitmen didn't had time to check the [pull request](https://github.com/zitmen/thunderstorm/pull/60), compile it and release it. But I think that can be improved if he could allow a few others to help with the maintenance (by adding them to the collaborators), then that can be solved.

I am thinking it's still good to keep one reference repo if possible. If that does not work, I think what you proposed is a good solution.

**Comment by oeway** [comment] 2018-08-29 13:42
I close this issue. Further discussion can go to a new issue. 
Thanks @cleterrier for the bug report.

**Closed as completed by oeway** 2018-08-29 13:42 UTC
